spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      encoding: UTF-8
  jpa:
    show-sql: true
data-live:
  datasource:
    url: jdbc:mysql://localhost:3306/test1
    username: root
    password: 08092003
data-backup:
  datasource:
    url: jdbc:mysql://localhost:3306/test2
    username: root
    password: 08092003
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/test2
#    username: root
#    password: 08092003
#    driver-class-name: com.mysql.cj.jdbc.Driver